name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy project files to EC2
      run: |
        rsync -az -e "ssh -i ~/.ssh/id_rsa" ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/Thapar_Go

    - name: SSH into EC2 and deploy
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd Thapar_Go
          echo "${{ secrets.ENV_FILE_PROD }}" > .env.prod
          docker compose -f docker-compose.yml -f docker-compose.prod.yml down
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
        EOF
